config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :items do
    match '/import', to: 'items#import', via: :post, on: :collection
  end
  root 'items#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/log_validation_errors.rb
# frozen_string_literal: true

module LogValidationErrors
  extend ActiveSupport::Concern

  included do
    after_validation :log_errors, if: proc { |m| m.errors }
  end

  def my_logger
    @@my_logger ||= Logger.new("#{Rails.root}/log/ongraph.log")
  end

  def log_errors
    unless errors.full_messages.blank?
      my_logger.debug "Product - #{title} (#{productid}) Failed to save!\n" + errors.full_messages.map { |i| " - #{i}" }.join("\n")
    end
  end
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  include LogValidationErrors
  # enum condition: ['like new', 'good', 'very good', 'new']
  # not using enum as keyword new is reserved
  # Alerted error - You tried to define an enum named "condition" on the model "Item", but this will generate a class method "new", which is already defined by Active Record.

  CONDITION = ['new', 'like new', 'good', 'very good'].freeze
  validates :condition, inclusion: { in: CONDITION }
  validates_length_of :productid, in: 10..13
  validates :sku, uniqueness: true
  validates :productid, uniqueness: { scope: :condition,
                                      message: 'Combination of ProductId and Condition is not unique' }

  def condition
    read_attribute(:condition).try(:downcase)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/concerns/log_errors.rb
# frozen_string_literal: true

module LogErrors
  extend ActiveSupport::Concern

  def my_logger
    @@my_logger ||= Logger.new("#{Rails.root}/log/ongraph.log")
  end

  def log_errors(e)
    my_logger.debug e.message unless e.blank?
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  include LogErrors

  def index
    @items = Item.all
  end

  def import
    CSV.foreach(params[:file].path, headers: true, header_converters: :symbol) do |row|
      filtered_row = row.to_hash.slice(:id, :productid, :condition, :sku, :title, :qty, :price)
      item = Item.find_or_create_by(filtered_row)
    end
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Process completed.' }
    end
  rescue StandardError => e
    log_errors(e)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/views/items/_item.html.erb
<tr>
  <td><%=item.productid %></td>
  <td><%=item.condition %></td>
  <td><%=item.sku %></td>
  <td><%=item.title %></td>
  <td><%=item.qty %></td>
  <td><%=item.price %></td>
</tr>

app/views/items/index.html.erb
<%= form_tag(import_items_path, multipart: true) do %>
<%= file_field_tag :file, required: true %>
<%= submit_tag( "Import" ) %>
<% end %>

<h2 style="color: greenyellow;"><%= notice %></h2>
<% unless @items.blank? %>
	<h1>Items</h1>
	<table>
		<tr>
			<th>ProductId</th>
			<th>Condition</th>
			<th>SKU</th>
			<th>Title</th>
			<th>Qty</th>
			<th>Price</th>
		</tr>
		<% @items.each do |item| %>
		<%= render item %>
		<% end %>
	</table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Product</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>